### ISSUE TITLE
Except placeholders

### ISSUE THREAD

**Issue by ronanflavio** [westonganger/input-case-enforcer#1]
Hi,

Could you help to except the enforcer for placeholders, letting the rules only to the input values? 

Thanks!

**Comment by westonganger** [comment]
Yes that is a good idea. I have now implemented this in master. Note that you must now include a CSS file, so re-read the instructions on readme. Please try out master and let me know if its working for you.

**Comment by ronanflavio** [comment]
Nice! It worked like a charm. Thanks bro =]

**Comment by westonganger** [comment]
v1.0.1 is now released.
